# Generated by Django 4.1 on 2023-11-18 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gatunek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
                ('opis', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Gra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=30)),
                ('wydawnictwo', models.IntegerField(choices=[(1, 'Portalgames'), (2, 'Rebel'), (3, 'Galakta'), (4, 'Luckyduckgames'), (5, 'Muduko'), (6, 'Naszaksięgarnia'), (7, 'Phalanx'), (8, 'G3'), (9, 'Trefl')], default=1)),
                ('min_gracze', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('max_gracze', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '10+')], default=1)),
                ('opis', models.CharField(blank=True, max_length=70)),
                ('gatunek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planszowki.gatunek')),
            ],
            options={
                'ordering': ['gatunek'],
            },
        ),
        migrations.CreateModel(
            name='Wypozyczajacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=30)),
                ('nazwisko', models.CharField(max_length=30)),
                ('nr_telefonu', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['nazwisko'],
            },
        ),
        migrations.CreateModel(
            name='Wypozyczenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wypozyczenia', models.DateField(verbose_name='data wypożyczenia')),
                ('tytul', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planszowki.gra')),
                ('wypozyczajacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planszowki.wypozyczajacy')),
            ],
        ),
    ]
