# Generated by Django 4.1 on 2023-11-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planszowki', '0002_rename_tytul_wypozyczenie_gra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gra',
            name='max_gracze',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '10+')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='gra',
            name='min_gracze',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1, null=True),
        ),
    ]
