# Generated by Django 4.1 on 2023-11-19 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planszowki', '0004_alter_gra_max_gracze_alter_gra_min_gracze'),
    ]

    operations = [
        migrations.AddField(
            model_name='wypozyczenie',
            name='uwagi',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='wypozyczajacy',
            name='nr_telefonu',
            field=models.CharField(max_length=9),
        ),
        migrations.CreateModel(
            name='Komentarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.CharField(blank=True, max_length=50)),
                ('ocena', models.IntegerField(blank=True, choices=[(1, '0'), (2, '1'), (3, '2'), (4, '3'), (5, '4'), (6, '5')], default=1, null=True)),
                ('gra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planszowki.gra')),
                ('wypozyczajacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planszowki.wypozyczajacy')),
            ],
        ),
    ]
