# Generated by Django 4.1 on 2023-11-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planszowki', '0005_wypozyczenie_uwagi_alter_wypozyczajacy_nr_telefonu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gra',
            name='max_gracze',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15')], default=1, null=True),
        ),
    ]
