# Generated by Django 4.1 on 2023-11-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planszowki', '0006_alter_gra_max_gracze'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wypozyczenie',
            name='data_wypozyczenia',
            field=models.DateField(verbose_name='data wypozyczenia'),
        ),
    ]
