# Generated by Django 4.1 on 2023-12-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planszowki', '0007_alter_wypozyczenie_data_wypozyczenia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gra',
            name='max_gracze',
        ),
        migrations.RemoveField(
            model_name='gra',
            name='min_gracze',
        ),
        migrations.AddField(
            model_name='gra',
            name='liczba_graczy',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
